chatbot:
  菜单:
    我是faith机器人:
      - 你在干什么
      - 你是谁
      - 你能做什么
  关于我:
    机器学习狂热粉丝，算法工程师:
      - 你的研究方向是什么
      - 你做什么的
      - 你的爱好
    硕士，正在进军Phd:
      - 你的学历
      - 你的教育等级
  查学校:
    select ws.name, c.name  from wechat_communitytoschool s, wechat_community c, wechat_school ws where c.name like '福宁花园' and s.communityId_id = c.communityId and ws.schoolId = s.schoolId:
      - 福宁花园的学区房
      
  学校评价:
    select description from wechat_school where name = '第八中学':
      - 八中怎么样
      - 八中如何
  查小区:
    SELECT name from wechat_community where communityId in (SELECT communityId_id from wechat_communitytoschool where schoolId in ( SELECT schoolId from wechat_school where name = '第八中学' )):
      - 八中的学区房
    

default:
  - 不知道
  - 试试换一个词语？