chatbot:
  菜单:
    我是faith机器人:
      - 你在干什么
      - 你是谁
      - 你能做什么
  关于我:
    机器学习狂热粉丝，算法工程师:
      - 你的研究方向是什么
      - 你做什么的
      - 你的爱好
    硕士，正在进军Phd:
      - 你的学历
      - 你的学位
      - 教育等级
  咨询:
    八中:
      - 柠溪的学区房
      - 香洲的学区房

default:
  - 不知道
  - 试试换一个词语？